import Image from 'tests/osg/Image';
import BlendColor from 'tests/osg/BlendColor';
import BoundingBox from 'tests/osg/BoundingBox';
import BoundingSphere from 'tests/osg/BoundingSphere';
import BufferArray from 'tests/osg/BufferArray';
import BufferArrayProxy from 'tests/osg/BufferArrayProxy';
import Camera from 'tests/osg/Camera';
import ComputeBoundsVisitor from 'tests/osg/ComputeBoundsVisitor';
import ComputeMatrixFromNodePath from 'tests/osg/ComputeMatrixFromNodePath';
import CullFace from 'tests/osg/CullFace';
import CullVisitor from 'tests/osg/CullVisitor';
import Depth from 'tests/osg/Depth';
import FrameBufferObject from 'tests/osg/FrameBufferObject';
import KdTree from 'tests/osg/KdTree';
import Light from 'tests/osg/Light';
import Matrix from 'tests/osg/Matrix';
import MatrixTransform from 'tests/osg/MatrixTransform';
import Node from 'tests/osg/Node';
import NodeVisitor from 'tests/osg/NodeVisitor';
import PagedLOD from 'tests/osg/PagedLOD';
import Plane from 'tests/osg/Plane';
import Quat from 'tests/osg/Quat';
import Shader from 'tests/osg/Shader';
import State from 'tests/osg/State';
import StateSet from 'tests/osg/StateSet';
import Switch from 'tests/osg/Switch';
import Texture from 'tests/osg/Texture';
import TextureCubeMap from 'tests/osg/TextureCubeMap';
import TextureManager from 'tests/osg/TextureManager';
import UpdateVisitor from 'tests/osg/UpdateVisitor';
import Uniform from 'tests/osg/Uniform';
import Utils from 'tests/osg/Utils';
import primitiveFunctor from 'tests/osg/primitiveFunctor';
import WebGLCaps from 'tests/osg/WebGLCaps';

export default function() {
    Image();
    BlendColor();
    BoundingBox();
    BoundingSphere();
    BufferArray();
    BufferArrayProxy();
    Camera();
    ComputeBoundsVisitor();
    ComputeMatrixFromNodePath();
    CullVisitor();
    CullFace();
    Depth();
    FrameBufferObject();
    KdTree();
    Light();
    Matrix();
    MatrixTransform();
    Node();
    NodeVisitor();
    Plane();
    PagedLOD();
    Quat();
    Shader();
    State();
    StateSet();
    Switch();
    Texture();
    TextureCubeMap();
    TextureManager();
    UpdateVisitor();
    Uniform();
    Utils();
    primitiveFunctor();
    WebGLCaps();
}
