import AutoTransform from 'osg/AutoTransform';
import BillboardAttribute from 'osg/BillboardAttribute';
import BlendColor from 'osg/BlendColor';
import BlendFunc from 'osg/BlendFunc';
import BoundingBox from 'osg/BoundingBox';
import BoundingSphere from 'osg/BoundingSphere';
import BufferArray from 'osg/BufferArray';
import BufferArrayProxy from 'osg/BufferArrayProxy';
import Camera from 'osg/Camera';
import ColorMask from 'osg/ColorMask';
import ComputeBoundsVisitor from 'osg/ComputeBoundsVisitor';
import ComputeMatrixFromNodePath from 'osg/computeMatrixFromNodePath';
import CullFace from 'osg/CullFace';
import CullingSet from 'osg/CullingSet';
import CullSettings from 'osg/CullSettings';
import CullStack from 'osg/CullStack';
import CullVisitor from 'osg/CullVisitor';
import Depth from 'osg/Depth';
import DrawArrayLengths from 'osg/DrawArrayLengths';
import DrawArrays from 'osg/DrawArrays';
import DrawElements from 'osg/DrawElements';
import EllipsoidModel from 'osg/EllipsoidModel';
import FrameBufferObject from 'osg/FrameBufferObject';
import FrameStamp from 'osg/FrameStamp';
import Geometry from 'osg/Geometry';
import { glm } from 'osg/glMatrix';
import GLObject from 'osg/GLObject';
import Image from 'osg/Image';
import ImageStream from 'osg/ImageStream';
import KdTree from 'osg/KdTree';
import KdTreeBuilder from 'osg/KdTreeBuilder';
import Light from 'osg/Light';
import LightSource from 'osg/LightSource';
import LineWidth from 'osg/LineWidth';
import Lod from 'osg/Lod';
import Material from 'osg/Material';
import osgjsMath from 'osg/math';
import MatrixTransform from 'osg/MatrixTransform';
import PooledResource from 'osg/PooledResource';
import PooledArray from 'osg/PooledArray';
import PooledMap from 'osg/PooledMap';
import Node from 'osg/Node';
import NodeVisitor from 'osg/NodeVisitor';
import notify from 'osg/notify';
import Object from 'osg/Object';
import Options from 'osg/Options';
import PagedLOD from 'osg/PagedLOD';
import Polytope from 'osg/Polytope';
import PointSizeAttribute from 'osg/PointSizeAttribute';
import Plane from 'osg/Plane';
import primitiveFunctor from 'osg/primitiveFunctor';
import primitiveIndexFunctor from 'osg/primitiveIndexFunctor';
import primitiveSet from 'osg/primitiveSet';
import Program from 'osg/Program';
import Projection from 'osg/Projection';
import RenderBin from 'osg/RenderBin';
import RenderLeaf from 'osg/RenderLeaf';
import RenderStage from 'osg/RenderStage';
import Shader from 'osg/Shader';
import Shape from 'osg/shape';
import StackObjectPairPool from 'osg/StackObjectPairPool';
import State from 'osg/State';
import StateAttribute from 'osg/StateAttribute';
import StateGraph from 'osg/StateGraph';
import StateSet from 'osg/StateSet';
import Switch from 'osg/Switch';
import Texture from 'osg/Texture';
import TextureCubeMap from 'osg/TextureCubeMap';
import Transform from 'osg/Transform';
import TriangleIndexFunctor from 'osg/TriangleIndexFunctor';
import Uniform from 'osg/Uniform';
import UpdateVisitor from 'osg/UpdateVisitor';
import utils from 'osg/utils';
import Viewport from 'osg/Viewport';
import Scissor from 'osg/Scissor';
import TransformEnums from 'osg/transformEnums';
import Timer from 'osg/Timer';
import TimerGPU from 'osg/TimerGPU';
import VertexArrayObject from 'osg/VertexArrayObject';
import WebGLCaps from 'osg/WebGLCaps';

var osg = {};
osg.AutoTransform = AutoTransform;
osg.BillboardAttribute = BillboardAttribute;
osg.BlendColor = BlendColor;
osg.BlendFunc = BlendFunc;
osg.BoundingBox = BoundingBox;
osg.BoundingSphere = BoundingSphere;
osg.BufferArray = BufferArray;
osg.BufferArrayProxy = BufferArrayProxy;
osg.ColorMask = ColorMask;
osg.Camera = Camera;
osg.ColorMask = ColorMask;
osg.ComputeBoundsVisitor = ComputeBoundsVisitor;
utils.objectMix(osg, ComputeMatrixFromNodePath);
osg.CullFace = CullFace;
osg.CullingSet = CullingSet;
osg.CullSettings = CullSettings;
osg.CullStack = CullStack;
osg.CullVisitor = CullVisitor;
osg.Depth = Depth;
osg.DrawArrayLengths = DrawArrayLengths;
osg.DrawArrays = DrawArrays;
osg.DrawElements = DrawElements;
osg.EllipsoidModel = EllipsoidModel;
osg.WGS_84_RADIUS_EQUATOR = EllipsoidModel.WGS_84_RADIUS_EQUATOR;
osg.WGS_84_RADIUS_POLAR = EllipsoidModel.WGS_84_RADIUS_POLAR;
osg.FrameBufferObject = FrameBufferObject;
osg.FrameStamp = FrameStamp;
osg.Geometry = Geometry;
osg.GLObject = GLObject;
osg.Image = Image;
osg.ImageStream = ImageStream;
osg.KdTree = KdTree;
osg.KdTreeBuilder = KdTreeBuilder;
osg.Light = Light;
osg.LightSource = LightSource;
osg.LineWidth = LineWidth;
osg.Lod = Lod;
osg.Material = Material;
utils.objectMix(osg, osgjsMath);
osg.MatrixTransform = MatrixTransform;
osg.PooledResource = PooledResource;
osg.PooledArray = PooledArray;
osg.PooledMap = PooledMap;
osg.Node = Node;
osg.NodeVisitor = NodeVisitor;
utils.objectMix(osg, notify);
osg.Object = Object;
osg.Options = Options;
osg.PagedLOD = PagedLOD;
osg.Plane = Plane;
osg.PointSizeAttribute = PointSizeAttribute;
osg.Polytope = Polytope;
osg.primitiveSet = primitiveSet;
osg.primitiveFunctor = primitiveFunctor;
osg.primitiveIndexFunctor = primitiveIndexFunctor;
osg.Program = Program;
osg.Projection = Projection;
osg.RenderBin = RenderBin;
osg.RenderLeaf = RenderLeaf;
osg.RenderStage = RenderStage;
osg.Shader = Shader;
utils.objectMix(osg, Shape);
osg.StackObjectPairPool = StackObjectPairPool;
osg.State = State;
osg.StateAttribute = StateAttribute;
osg.StateGraph = StateGraph;
osg.StateSet = StateSet;
osg.Scissor = Scissor;
osg.Switch = Switch;
osg.Texture = Texture;
osg.TextureCubeMap = TextureCubeMap;
osg.Transform = Transform;
osg.TriangleIndexFunctor = TriangleIndexFunctor;
osg.Uniform = Uniform;
osg.UpdateVisitor = UpdateVisitor;
utils.objectMix(osg, utils);
osg.Viewport = Viewport;
osg.VertexArrayObject = VertexArrayObject;
osg.vec2 = glm.vec2;
osg.vec3 = glm.vec3;
osg.vec4 = glm.vec4;
osg.quat = glm.quat;
osg.mat3 = glm.mat3;
osg.mat4 = glm.mat4;

osg.Transform.RELATIVE_RF = TransformEnums.RELATIVE_RF;
osg.Transform.ABSOLUTE_RF = TransformEnums.ABSOLUTE_RF;
osg.Timer = Timer;
osg.TimerGPU = TimerGPU;
osg.WebGLCaps = WebGLCaps;

export default osg;
