import utils from 'osg/utils';
import Animation from 'osgAnimation/animation';
import SkinningAttribute from 'osgAnimation/SkinningAttribute';
import AnimationUpdateCallback from 'osgAnimation/AnimationUpdateCallback';
import BasicAnimationManager from 'osgAnimation/BasicAnimationManager';
import Bone from 'osgAnimation/Bone';
import Channel from 'osgAnimation/channel';
import CollectAnimationUpdateCallbackVisitor from 'osgAnimation/CollectAnimationUpdateCallbackVisitor';
import Easing from 'osgAnimation/easing';
import Interpolator from 'osgAnimation/interpolator';
import MorphAttribute from 'osgAnimation/MorphAttribute';
import MorphGeometry from 'osgAnimation/MorphGeometry';
import RigGeometry from 'osgAnimation/RigGeometry';
import Skeleton from 'osgAnimation/Skeleton';
import StackedMatrix from 'osgAnimation/StackedMatrix';
import StackedQuaternion from 'osgAnimation/StackedQuaternion';
import StackedRotateAxis from 'osgAnimation/StackedRotateAxis';
import StackedScale from 'osgAnimation/StackedScale';
import StackedTranslate from 'osgAnimation/StackedTranslate';
import UpdateBone from 'osgAnimation/UpdateBone';
import UpdateMatrixTransform from 'osgAnimation/UpdateMatrixTransform';
import UpdateMorph from 'osgAnimation/UpdateMorph';
import UpdateSkeleton from 'osgAnimation/UpdateSkeleton';

var osgAnimation = {};

utils.objectMix(osgAnimation, Easing);
utils.objectMix(osgAnimation, Interpolator);
osgAnimation.Animation = Animation;
osgAnimation.SkinningAttribute = SkinningAttribute;
osgAnimation.AnimationUpdateCallback = AnimationUpdateCallback;
osgAnimation.BasicAnimationManager = BasicAnimationManager;
osgAnimation.Bone = Bone;
osgAnimation.Channel = Channel;
osgAnimation.CollectAnimationUpdateCallbackVisitor = CollectAnimationUpdateCallbackVisitor;
osgAnimation.MorphAttribute = MorphAttribute;
osgAnimation.MorphGeometry = MorphGeometry;
osgAnimation.RigGeometry = RigGeometry;
osgAnimation.Skeleton = Skeleton;
osgAnimation.StackedMatrix = StackedMatrix;
osgAnimation.StackedQuaternion = StackedQuaternion;
osgAnimation.StackedRotateAxis = StackedRotateAxis;
osgAnimation.StackedScale = StackedScale;
osgAnimation.StackedTranslate = StackedTranslate;
osgAnimation.UpdateBone = UpdateBone;
osgAnimation.UpdateMatrixTransform = UpdateMatrixTransform;
osgAnimation.UpdateMorph = UpdateMorph;
osgAnimation.UpdateSkeleton = UpdateSkeleton;

export default osgAnimation;
